/**
 * @layer infrastructure
 * @unit fuse-hooks-engine
 *
 * DefaultHooksYamlGenerator — デフォルト .harness-hooks.yml 生成
 */
import * as fs from 'node:fs';
import * as path from 'node:path';

const DEFAULT_HOOKS_YAML = `# .harness-hooks.yml — GSDLC Quality Harness FUSE/Hooks Configuration
# Generated by: harness fuse:mount
version: "1.0"

fuse:
  enabled: true
  mount_point: ".workspace"
  source: "."
  exclude_from_mount:
    - node_modules
    - .git
    - .harness
    - dist

hooks:
  preWrite:
    - name: "protect-config"
      description: "設定ファイルの直接編集をブロック"
      patterns:
        - "harness.config.json"
        - ".claude/settings.json"
        - "package.json"
      action: block
      message: "設定ファイルはCLI経由で変更してください"

    - name: "protect-principles"
      description: "原則ドキュメントの編集をブロック"
      patterns:
        - "docs/principles/**"
      action: block
      message: "原則ドキュメントは immutable です"

    - name: "protect-secrets"
      description: "機密ファイルの作成・編集をブロック"
      patterns:
        - "**/.env"
        - "**/.env.*"
        - "**/*.key"
        - "**/*.pem"
        - "**/*.p12"
        - "**/credentials.json"
        - "**/secret*.json"
      action: block
      message: "機密ファイルへの書き込みはブロックされています"

  postWrite:
    - name: "run-lint"
      description: "編集後に自動リント実行"
      patterns:
        - "scripts/harness/**/*.ts"
      action: run-shell
      script: "npx harness lint --target {file}"
      timeout: 30000
      failOnNonZero: false

    - name: "check-metadata"
      description: "メタデータ整合性チェック"
      patterns:
        - "scripts/harness/**/*.ts"
      action: run-shell
      script: "npx harness validate-metadata {file}"
      timeout: 10000
      failOnNonZero: false

  preRead:
    - name: "block-secrets-read"
      description: "機密ファイルの読み取りをブロック"
      patterns:
        - "**/.env"
        - "**/.env.*"
        - "**/*.key"
        - "**/*.pem"
        - "**/*.p12"
        - "**/credentials.json"
        - "**/secret*.json"
      action: block
      message: "機密ファイルの読み取りはブロックされています"

  preBash:
    - name: "block-destructive"
      description: "破壊的コマンドをブロック"
      commands:
        - pattern: "rm -rf"
          action: block
          message: "rm -rf は禁止されています"
        - pattern: "git push --force"
          action: block
          message: "force push は禁止されています"
        - pattern: "git reset --hard"
          action: block
          message: "git reset --hard は禁止されています"

  onComplete:
    - name: "completion-gate"
      description: "完了ゲートチェック"
      action: run-shell
      script: "npx harness hooks:gate-check --story {storyId}"
      timeout: 60000
      failOnNonZero: true

adapters:
  claude_code:
    pre_tool_use: true
    post_tool_use: true
    stop_hook: true
  codex:
    pre_tool_use: false
    post_tool_use: false
    stop_hook: false
`;

export class DefaultHooksYamlGenerator {
  generate(): string {
    return DEFAULT_HOOKS_YAML;
  }

  async writeIfNotExists(targetDir: string): Promise<{ created: boolean; path: string }> {
    const filePath = path.join(targetDir, '.harness-hooks.yml');

    if (fs.existsSync(filePath)) {
      return { created: false, path: filePath };
    }

    fs.writeFileSync(filePath, DEFAULT_HOOKS_YAML, 'utf-8');
    return { created: true, path: filePath };
  }
}
