/**
 * @layer infrastructure
 * @unit fuse-hooks-engine
 */

import { exec } from 'node:child_process';
import * as fs from 'node:fs/promises';
import * as path from 'node:path';
import { promisify } from 'node:util';
import { FuseHooksEngineDomainError } from '../../domain/errors/fuse-hooks-engine-domain-error.js';
import { DestructiveCommandList } from '../../domain/value-objects/destructive-command-list.js';

const execAsync = promisify(exec);

const DEFAULT_DESTRUCTIVE_COMMANDS = [
  { command: 'rm', dangerousOptions: ['-rf', '-fr'] },
  { command: 'git', dangerousOptions: ['reset --hard'] },
];

export interface ShellWrapperAdapterOptions {
  destructiveCommandList?: DestructiveCommandList;
}

export class ShellWrapperAdapter {
  private readonly destructiveCommandList: DestructiveCommandList;

  constructor(options?: ShellWrapperAdapterOptions) {
    this.destructiveCommandList =
      options?.destructiveCommandList ??
      DestructiveCommandList.create(DEFAULT_DESTRUCTIVE_COMMANDS)._unsafeUnwrap();
  }

  async execute(script: string, options: { timeout?: number; failOnNonZero: boolean }) {
    if (this.destructiveCommandList.isDestructive(script)) {
      throw new FuseHooksEngineDomainError(
        'DESTRUCTIVE_COMMAND_BLOCKED',
        'Destructive command blocked',
      );
    }

    try {
      const result = await execAsync(script, {
        timeout: options.timeout,
        shell: '/bin/zsh',
      });
      return {
        exitCode: 0,
        stdout: result.stdout,
        stderr: result.stderr,
      };
    } catch (error) {
      const failure = error as { stdout?: string; stderr?: string; code?: number };
      if (options.failOnNonZero) {
        throw new FuseHooksEngineDomainError(
          'SHELL_HOOK_FAILED',
          failure.stderr ?? 'Shell hook failed',
        );
      }
      return {
        exitCode: typeof failure.code === 'number' ? failure.code : 1,
        stdout: failure.stdout ?? '',
        stderr: failure.stderr ?? '',
      };
    }
  }

  async generateWrappers(wrapperDir: string): Promise<string[]> {
    await fs.mkdir(wrapperDir, { recursive: true });
    const generated: string[] = [];

    for (const entry of this.destructiveCommandList.commands) {
      const scriptPath = path.join(wrapperDir, entry.command);
      const dangerousChecks = entry.dangerousOptions
        .map((opt) => `  *${opt}*) echo "[HARNESS] Blocked: ${entry.command} with ${opt}" >&2; exit 1;;`)
        .join('\n');

      const script = `#!/bin/sh
# Generated by HARNESS ShellWrapperAdapter
ORIGINAL=$(PATH=$(echo "$PATH" | sed "s|${wrapperDir}:||g") command -v ${entry.command})
case "$*" in
${dangerousChecks}
  *) exec "$ORIGINAL" "$@";;
esac
`;
      await fs.writeFile(scriptPath, script, { mode: 0o755 });
      generated.push(scriptPath);
    }

    return generated;
  }

  getModifiedPath(wrapperDir: string): string {
    const currentPath = process.env.PATH ?? '';
    return `${wrapperDir}${path.delimiter}${currentPath}`;
  }
}
